### ISSUE TITLE
Implement Peak-Load Pricing

### ISSUE THREAD

**Issue by kanakpandit17** [im-ukr/SmartStay#14]
Peak-Load Pricing: Prices are lowered when demand is not as high as expected(Decrease prices by 10%-15%) , but prices can also be increased when demand is higher than expected(Increase prices by 10%-20%)

**Comment by im-ukr77** [comment]
completed

**Comment by kanakpandit17** [comment]
Bro this is not done yet, please reopen the issue. We have to set a threshold value above and below which there will be discounts or price surge based on demand and supply of rooms.

**Comment by im-ukr77** [comment]
oh sorry, i misinterpreted the message.

**Comment by im-ukr77** [comment]
finally done!
