### ISSUE TITLE
Hardcoded in loyalty discount

### ISSUE THREAD

**Issue by kanakpandit17** [im-ukr/SmartStay#6]
You are giving loyalty to only one email id, and it's hardcoded. Admin should add in the UI loyalty email ids which will automatically get loyalty discount.
# Function to apply loyalty discount
def apply_loyalty_discount(current_price, guest):
    previous_price = current_price
    if guest.email_id == 'ukr@abc.com':
        current_price = int(current_price * 0.8)  # Apply 20% discount
    
    percentage_change = ((current_price - previous_price) / previous_price) * 100
    print(f"Loyalty Discount: {current_price} ({f'{percentage_change:.2f}%' if percentage_change != 0 else 'No Change'})")
    return current_price, f"{percentage_change:.2f}%" if percentage_change != 0 else "No Change"

**Comment by im-ukr77** [comment]
Can add mutiple email ids using 'IN', but yes UI is on wishlist, we'll have to see how we can proceed with it.

# Function to apply loyalty discount
def apply_loyalty_discount(current_price, guest):
    previous_price = current_price
    if guest.email_id in ['ukr@abc.in','ukr@abc.com']:
        current_price = int(current_price * 0.8)  # Apply 20% discount
